version: '3.8'

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  agent:
    build: .
    environment:
      - REDIS_URL=redis://redis:6379/0
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
    depends_on:
      - redis